/*
* generated by Xtext
*/
package me.shiv.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import me.shiv.dsl.services.AnatomyGrammarAccess;

public class AnatomyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AnatomyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected me.shiv.dsl.parser.antlr.internal.InternalAnatomyParser createParser(XtextTokenStream stream) {
		return new me.shiv.dsl.parser.antlr.internal.InternalAnatomyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AnatomyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AnatomyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
