/*
* generated by Xtext
*/
package me.shiv.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AnatomyStandaloneSetup extends AnatomyStandaloneSetupGenerated{

	public static void doSetup() {
		new AnatomyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

