/*
 * generated by Xtext
 */
package me.shiv.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnatomyRuntimeModule extends me.shiv.dsl.AbstractAnatomyRuntimeModule {

}
