/*
 * generated by Xtext
 */
package me.shiv.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import me.shiv.dsl.ui.internal.AnatomyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnatomyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnatomyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnatomyActivator.getInstance().getInjector(AnatomyActivator.ME_SHIV_DSL_ANATOMY);
	}
	
}
