/**
 * generated by Xtext
 */
package me.shiv.dsl.ui.contentassist;

import me.shiv.dsl.ui.contentassist.AbstractAnatomyProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AnatomyProposalProvider extends AbstractAnatomyProposalProvider {
}
