/*
 * generated by Xtext
 */
package me.shiv.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AnatomyUiModule extends me.shiv.dsl.ui.AbstractAnatomyUiModule {
	public AnatomyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
